### ISSUE TITLE
Issue with running keep alive script

### ISSUE THREAD

**Issue by gep13** [hubot-scripts/hubot-heroku-keepalive#23]
I am having an issue that I am hoping you might be able to give me some pointers on...

I have 4 apps set up in Heroku, each of them is a Hubot instance, that is linked to a Gitter chat room.  The Hubot instance itself is working as I would expect them to, however, 2 out of the 4 applications fail to come back to life each morning.  As you can see here:

![image](https://cloud.githubusercontent.com/assets/1271146/12871720/e6f825a8-cd7f-11e5-895e-612bf6a505e7.png)

From what I can tell, each application is configured exactly the same way, so I can't understand why two of them don't wake up.

Can you suggest anything that I can look into?  Thanks!

**Comment by treby** [comment]
I think you don't set some environment variables (or / and) heroku scheduler settings proper time.
There are three key points.

- [Heroku Scheduler](https://devcenter.heroku.com/articles/scheduler) settings
- `HUBOT_HEROKU_WAKEUP_TIME`
- `HUBOT_HEROKU_SLEEP_TIME`

You should configure times as `HUBOT_HEROKU_WAKEUP_TIME` < (some requests from heroku scheduler) < `HUBOT_HEROKU_SLEEP_TIME`.Remember, heroku scheduler settings should be set as UTC. Sometimes we use another timezone on heroku app (by set `TZ` environments variable).

And on the current heroku free plan, [the dyno must sleep 6 hours in a 24 hour period](https://www.heroku.com/pricing). Don't you try to use the heroku instance over 18 hours in a 24 hour period? If you try so, the request should be failure because of the "must sleep" limitation.

You can check what's happend around the time that heroku scheduler triggers by checking the heroku logs file(`heroku logs`). And by using `heroku ps` command, you can check how long time dyno working in a 24 hour period.

Thanks.

**Comment by gep13** [comment]
@treby thank you very much for getting back to me about this.

I have the following configuration in my environment variables:

![image](https://cloud.githubusercontent.com/assets/1271146/12874623/f5b67546-cdce-11e5-8566-63a1a8f97f6f.png)

and I have this in my Scheduler:

![image](https://cloud.githubusercontent.com/assets/1271146/12874642/4433037e-cdcf-11e5-9c5f-f1d3d57c518e.png)

And as I type this, I think I see what the issue is :smile: I need to change the scheduler to run as some point after 06:00.

Let me give that a try.  Thanks again!

**Comment by gep13** [comment]
@treby I just wanted to follow up to say that this is now working as expected.  Thanks!
