### ISSUE TITLE
Take into account Heroku's new idling policy

### ISSUE THREAD

**Issue by ivancamilov** [hubot-scripts/hubot-heroku-keepalive#8]
In the past few days, Heroku made this announcement:

> Another important change has to do with dyno idling, or ‘sleeping’. While non-paid apps have always slept after an activity timeout, some apps used automatic pinging services to prevent that behavior. free dynos are allowed 18 hours awake per 24 hour period, and over the next few weeks we will begin to notify users of apps that exceed that limit
> - Heroku

How should we take this into account? set a variable for hubot's "waking hours"?

**Comment by technicalpickles** [comment]
https://blog.heroku.com/archives/2015/5/7/heroku-free-dynos and https://blog.heroku.com/archives/2015/5/7/new-dyno-types-public-beta for context

**Comment by y16ra** [comment]
>  set a variable for hubot's "waking hours"

+1

**Comment by hirefrank** [comment]
+1 Any update here?

**Comment by technicalpickles** [comment]
I am not currently running hubot on Heroku, so any help from the community would be appreciated. There will be need to be documentation updates to https://github.com/github/hubot/blob/master/docs/deploying/heroku.md too.

**Comment by alexeyza** [comment]
+1 on setting a variable for the waking hours (18 out of 24).

**Comment by tfrevert** [comment]
+1 for setting waking hours between x and y.

**Comment by umer936** [comment]
Has this been done yet? I am interested in having the bot sleep and wake up at specific times.

**Comment by patsissons** [comment]
@umer936 there has been some discussion in pull request #9

**Comment by kgann** [comment]
:+1: for setting waking hours

**Comment by lourinaldi** [comment]
:+1: for setting waking hours

**Comment by technicalpickles** [comment]
Anyone having problems with their Hubot's on free dynos will need to:

* `npm update hubot-heroku-keepalive` to update the package
* follow instructions in [the readme](https://github.com/hubot-scripts/hubot-heroku-keepalive#configuring) to configure wakeup and sleep times, and configure the heroku scheduler to wake hubot up.

Alternatively, if you update to a hobby dyno, you can either unset HUBOT_HEROKU_KEEPALIVE_URL or remove it as a script in `external-scripts.json` in order to turn it off, since hobby dynos don't sleep.

**Comment by msurguy** [comment]
I had to run `npm remove hubot-heroku-keepalive --save` and then `npm install hubot-heroku-keepalive --save` to get the latest version, `update` command didn't work since the version is not in the 0.x.x range
